# Generated by Django 5.2.14 on 2026-05-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_image_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
